// examples/react-shadcn/src/App.tsx
import type { FormDefinition } from '@formhaus/core';
import { FormRenderer } from '@formhaus/react';
import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { components } from './component-map';
import json from './definition.json';
import { FormActions } from './FormActions';
import { StepProgress } from './StepProgress';

const definition = json as FormDefinition;

export function App() {
  const [submitted, setSubmitted] = useState<Record<string, unknown> | null>(null);

  return (
    <main className="mx-auto max-w-md px-4 py-8">
      <Card>
        <CardHeader>
          <CardTitle>{definition.title}</CardTitle>
        </CardHeader>
        <CardContent>
          {submitted ? (
            <pre className="text-sm">{JSON.stringify(submitted, null, 2)}</pre>
          ) : (
            <FormRenderer
              definition={definition}
              components={components}
              ActionsComponent={FormActions}
              ProgressComponent={StepProgress}
              onSubmit={setSubmitted}
            />
          )}
        </CardContent>
      </Card>
    </main>
  );
}

// examples/vue-vuetify/src/App.vue
<script setup>
import { FormRenderer } from '@formhaus/vue';
import { components } from './component-map';
import FormActions from './actions/FormActions.vue';
import StepProgress from './actions/StepProgress.vue';
import definition from './definition.json';

function onSubmit(values) {
  console.log('Submitted:', values);
}
</script>

<template>
  <v-app>
    <v-container style="max-width: 600px">
      <FormRenderer
        :definition="definition"
        :components="components"
        :actions-component="FormActions"
        :progress-component="StepProgress"
        @submit="onSubmit"
      />
    </v-container>
  </v-app>
</template>
