// examples/vue-vuetify/src/fields/CheckboxField.vue
<script setup>
defineProps({
  field: { type: Object, required: true },
  value: { default: undefined },
  error: { type: String, default: undefined },
  loading: { type: Boolean, default: false },
  disabled: { type: Boolean, default: false },
});

const emit = defineEmits(['update:value', 'blur', 'focus']);
</script>

<template>
  <v-checkbox
    :id="field.key"
    :label="field.label"
    :model-value="!!value"
    :error-messages="error ? [error] : []"
    :hint="field.helperText"
    :persistent-hint="!!field.helperText"
    :disabled="disabled || loading"
    @update:model-value="(v) => emit('update:value', v)"
    @blur="emit('blur')"
    @focus="emit('focus')"
  />
</template>

// examples/react-mui/src/fields/CheckboxField.tsx
import type { FieldComponentProps } from '@formhaus/react';
import Checkbox from '@mui/material/Checkbox';
import FormControlLabel from '@mui/material/FormControlLabel';
import FormHelperText from '@mui/material/FormHelperText';

export function CheckboxField({
  field,
  value,
  error,
  loading,
  disabled,
  onChange,
}: FieldComponentProps) {
  return (
    <div style={{ marginTop: 8, marginBottom: 4 }}>
      <FormControlLabel
        control={
          <Checkbox
            id={field.key}
            checked={!!value}
            onChange={(e) => onChange(e.target.checked)}
            disabled={disabled || loading}
          />
        }
        label={field.label}
      />
      {error && <FormHelperText error>{error}</FormHelperText>}
      {!error && field.helperText && <FormHelperText>{field.helperText}</FormHelperText>}
    </div>
  );
}
