// examples/vue-vuetify/src/fields/FileField.vue
<script setup>
defineProps({
  field: { type: Object, required: true },
  value: { default: undefined },
  error: { type: String, default: undefined },
  loading: { type: Boolean, default: false },
  disabled: { type: Boolean, default: false },
});

const emit = defineEmits(['update:value', 'blur', 'focus']);
</script>

<template>
  <v-file-input
    :id="field.key"
    :label="field.label"
    :accept="field.accept"
    :error-messages="error ? [error] : []"
    :hint="field.helperText"
    :persistent-hint="!!field.helperText"
    :disabled="disabled || loading"
    @update:model-value="(files) => emit('update:value', files && files.length > 0 ? files[0] : null)"
    @blur="emit('blur')"
    @focus="emit('focus')"
  />
</template>

// examples/react-mui/src/fields/FileField.tsx
import type { FieldComponentProps } from '@formhaus/react';
import Button from '@mui/material/Button';
import FormHelperText from '@mui/material/FormHelperText';

export function FileField({
  field,
  error,
  loading,
  disabled,
  onChange,
}: FieldComponentProps) {
  return (
    <div style={{ marginTop: 16, marginBottom: 8 }}>
      <label style={{ display: 'block', marginBottom: 4, fontSize: 14, color: 'rgba(0,0,0,0.6)' }}>
        {field.label}
      </label>
      <Button variant="outlined" component="label" disabled={disabled || loading}>
        Choose file
        <input
          id={field.key}
          type="file"
          accept={field.accept}
          hidden
          onChange={(e) => {
            const files = e.target.files;
            onChange(files && files.length > 0 ? files[0] : null);
          }}
        />
      </Button>
      {error && <FormHelperText error>{error}</FormHelperText>}
      {!error && field.helperText && <FormHelperText>{field.helperText}</FormHelperText>}
    </div>
  );
}
