// packages/vue/src/FormField.vue
<script setup lang="ts">
import type { FormField } from '@formhaus/core';
import { type Component, computed } from 'vue';
import { defaultFieldComponents } from './constants';
import type { FieldComponentMap } from './types';

const props = defineProps<{
  field: FormField;
  value: unknown;
  error?: string;
  loading?: boolean;
  disabled?: boolean;
  components?: Partial<FieldComponentMap>;
}>();

const emit = defineEmits<{
  (e: 'update:value', value: unknown): void;
  (e: 'blur'): void;
}>();

const fieldComponent = computed<Component | null>(() => {
  const custom = props.components?.[props.field.type];
  if (custom) return custom;
  return defaultFieldComponents[props.field.type] ?? null;
});
</script>

<template>
  <component
    :is="fieldComponent"
    v-if="fieldComponent"
    :field="props.field"
    :value="props.value"
    :error="props.error"
    :loading="props.loading"
    :disabled="props.disabled"
    @update:value="(v: unknown) => emit('update:value', v)"
    @blur="emit('blur')"
  />
  <div v-else class="fh-field--unsupported">
    Unsupported field type: {{ props.field.type }}
  </div>
</template>

// packages/react/src/FormField.tsx
import type { FormField as FormFieldType } from '@formhaus/core';
import type { FieldComponentMap, FieldComponentProps } from './types';

interface FormFieldProps {
  field: FormFieldType;
  value: unknown;
  error?: string;
  loading?: boolean;
  disabled?: boolean;
  components?: FieldComponentMap;
  onChange: (value: unknown) => void;
  onBlur: () => void;
  onFocus?: () => void;
}

export function FormField({
  field,
  value,
  error,
  loading,
  disabled,
  components,
  onChange,
  onBlur,
  onFocus,
}: FormFieldProps) {
  const Component = components?.[field.type];

  if (!Component) {
    return <div>Unsupported field type: {field.type}</div>;
  }

  return (
    <Component
      field={field}
      value={value}
      error={error}
      loading={loading}
      disabled={disabled}
      onChange={onChange}
      onBlur={onBlur}
      onFocus={onFocus}
    />
  );
}
