// packages/vue/src/FormActions.vue
<script setup lang="ts">
import { type FormAction, evaluateCondition } from '@formhaus/core';
import type { FormActionsProps } from './types';

const props = defineProps<FormActionsProps>();

const emit = defineEmits<{
  (e: 'submit'): void;
  (e: 'next'): void;
  (e: 'prev'): void;
  (e: 'cancel'): void;
  (e: 'primary'): void;
  (e: 'action', name: string): void;
}>();

function isActionDisabled(action: FormAction | undefined): boolean {
  if (props.loading) return true;
  if (!action?.disabled || action.disabled.length === 0) return false;
  return action.disabled.every((c) => evaluateCondition(c, props.values ?? {}));
}

function getButtonClass(variant?: string): string {
  switch (variant) {
    case 'secondary':
      return 'fh-form-actions__button--secondary';
    case 'text':
      return 'fh-form-actions__button--text';
    default:
      return 'fh-form-actions__button--primary';
  }
}

function onPrimaryClick() {
  if (props.primaryLabel !== undefined) {
    emit('primary');
  } else if (props.isMultiStep && !props.isLastStep) {
    emit('next');
  } else {
    emit('submit');
  }
}

function getPrimaryLabel(): string {
  if (props.primaryLabel !== undefined) return props.primaryLabel;
  if (props.isMultiStep && !props.isLastStep) return 'Continue';
  return props.submitAction?.label ?? 'Submit';
}

function getShouldShowBack(): boolean {
  if (props.showBack !== undefined) return props.showBack;
  return props.isMultiStep && !props.isFirstStep && props.backAction !== false;
}

function getBackLabel(): string {
  if (props.backLabel !== undefined) return props.backLabel;
  return (typeof props.backAction === 'object' ? props.backAction?.label : undefined) ?? 'Back';
}
</script>

<template>
  <div class="fh-form-actions">
    <div class="fh-form-actions__secondary">
      <button
        v-if="getShouldShowBack()"
        type="button"
        :class="['fh-form-actions__button', typeof props.backAction === 'object' ? getButtonClass(props.backAction?.variant) : 'fh-form-actions__button--text']"
        :disabled="props.loading"
        @click="emit('prev')"
      >
        {{ getBackLabel() }}
      </button>
      <button
        v-if="props.cancelAction"
        type="button"
        :class="['fh-form-actions__button', getButtonClass(props.cancelAction.variant)]"
        :disabled="props.loading"
        @click="emit('cancel')"
      >
        {{ props.cancelAction.label }}
      </button>
    </div>
    <button
      v-if="props.showPrimary !== false"
      type="button"
      class="fh-form-actions__button fh-form-actions__button--primary"
      :disabled="isActionDisabled(props.isMultiStep && !props.isLastStep ? undefined : props.submitAction)"
      @click="onPrimaryClick"
    >
      {{ getPrimaryLabel() }}
    </button>
  </div>
</template>

// packages/react/src/FormActions.tsx
import { evaluateCondition } from '@formhaus/core';
import type { FormAction } from '@formhaus/core';
import type { FormActionsProps } from './types';

function isActionDisabled(
  action: FormAction | undefined,
  values: Record<string, unknown>,
  loading?: boolean,
): boolean {
  if (loading) return true;
  if (!action?.disabled || action.disabled.length === 0) return false;
  return action.disabled.every((c) => evaluateCondition(c, values));
}

function buttonClass(action: FormAction | false | undefined, variant: NonNullable<FormAction['variant']>): string {
  return `fh-form-actions__button fh-form-actions__button--${(action && action.variant) || variant}`;
}

export function FormActions({
  submitAction,
  backAction,
  cancelAction,
  skipAction,
  isFirstStep,
  isLastStep,
  isMultiStep,
  loading,
  showPrimary = true,
  values = {},
  onSubmit,
  onNext,
  onPrev,
  onCancel,
  onSkip,
  primaryLabel: primaryLabelProp,
  showBack: showBackProp,
  backLabel: backLabelProp,
  showSkip: showSkipProp,
  skipLabel: skipLabelProp,
  onPrimary: onPrimaryProp,
}: FormActionsProps) {
  const showBack = showBackProp ?? (isMultiStep && !isFirstStep && backAction !== false);
  const backLabel = backLabelProp ?? (typeof backAction === 'object' ? (backAction?.label ?? 'Back') : 'Back');
  const showSkip = !!onSkip && (showSkipProp ?? (isMultiStep && !!skipAction));
  const skipLabel = skipLabelProp ?? skipAction?.label ?? 'Skip';
  const primaryLabel = primaryLabelProp ?? (isMultiStep && !isLastStep ? 'Continue' : (submitAction?.label ?? 'Submit'));

  const primaryDisabled = isActionDisabled(
    isMultiStep && !isLastStep ? undefined : submitAction,
    values,
    loading,
  );

  function handlePrimary() {
    if (onPrimaryProp) {
      onPrimaryProp();
    } else if (isMultiStep && !isLastStep) {
      onNext();
    } else {
      onSubmit();
    }
  }

  return (
    <div className="fh-form-actions">
      <div className="fh-form-actions__secondary">
        {showBack && (
          <button type="button" className={buttonClass(backAction, 'secondary')} disabled={loading} onClick={onPrev}>
            {backLabel}
          </button>
        )}
        {cancelAction && (
          <button type="button" className={buttonClass(cancelAction, 'text')} disabled={loading} onClick={onCancel}>
            {cancelAction.label}
          </button>
        )}
        {showSkip && (
          <button type="button" className={buttonClass(skipAction, 'text')} disabled={loading} onClick={onSkip}>
            {skipLabel}
          </button>
        )}
      </div>
      {showPrimary && <button
        type="button"
        className="fh-form-actions__button fh-form-actions__button--primary"
        disabled={primaryDisabled}
        aria-busy={loading}
        onClick={handlePrimary}
      >
        {primaryLabel}
      </button>}
    </div>
  );
}
