// packages/vue/src/cloud/FormhausForm.vue
<script setup lang="ts">
import { computed } from 'vue';
import FormRenderer from '../FormRenderer.vue';
import type { FormhausFormProps } from './types';
import { useCloudForm } from './useCloudForm';

const props = defineProps<FormhausFormProps>();
const emit = defineEmits<{ success: [submission: { id: string; values: Record<string, unknown> }] }>();

const { definition, loadError, errors, done, submit } = useCloudForm({
  id: () => props.id,
  apiBase: () => props.apiBase,
  onSuccess: (submission) => emit('success', submission),
  onError: () => props.onError,
});

const rendererProps = computed(() => {
  const { id, apiBase, ...rest } = props;
  return rest;
});
</script>

<template>
  <p v-if="loadError" role="alert" class="fh-form__error">{{ loadError.message }}</p>
  <div v-else-if="!definition" class="fh-form" aria-busy="true"><slot name="fallback" /></div>
  <slot v-else-if="done" name="success">
    <p role="status" class="fh-form__success">Thank you. Your response was submitted.</p>
  </slot>
  <FormRenderer v-else v-bind="rendererProps" :definition="definition" :errors="errors" :submit-handler="submit" />
</template>

// packages/react/src/cloud/FormhausForm.tsx
import { FormRenderer } from '../FormRenderer';
import type { FormhausFormProps } from './types';
import { useCloudForm } from './useCloudForm';

export function FormhausForm({ id, apiBase, onSuccess, fallback, success, ...rendererProps }: FormhausFormProps) {
  const { definition, loadError, errors, done, submit } = useCloudForm({ id, apiBase, onSuccess, onError: rendererProps.onError });
  if (loadError) return <p role="alert" className="fh-form__error">{loadError.message}</p>;
  if (!definition) return <div className="fh-form" aria-busy="true">{fallback}</div>;
  if (done) return <>{success ?? <p role="status" className="fh-form__success">Thank you. Your response was submitted.</p>}</>;
  return <FormRenderer {...rendererProps} definition={definition} errors={errors} onSubmit={submit} />;
}
