// examples/vue-vuetify/src/actions/FormActions.vue
<script setup>
defineProps({
  primaryLabel: { type: String, default: undefined },
  showPrimary: { type: Boolean, default: true },
  showBack: { type: Boolean, default: false },
  backLabel: { type: String, default: undefined },
  cancelAction: { type: Object, default: undefined },
  loading: { type: Boolean, default: false },
});

const emit = defineEmits(['primary', 'prev', 'cancel']);
</script>

<template>
  <div style="display: flex; justify-content: space-between; gap: 8px; padding-top: 16px">
    <div style="display: flex; gap: 8px">
      <v-btn v-if="showBack" variant="outlined" :disabled="loading" @click="emit('prev')">
        {{ backLabel }}
      </v-btn>
      <v-btn v-if="cancelAction" variant="text" :disabled="loading" @click="emit('cancel')">
        {{ cancelAction.label }}
      </v-btn>
    </div>
    <v-btn v-if="showPrimary" color="primary" :loading="loading" @click="emit('primary')">
      {{ primaryLabel }}
    </v-btn>
  </div>
</template>

// examples/react-shadcn/src/FormActions.tsx
import type { FormActionsProps } from '@formhaus/react';
import { Button } from '@/components/ui/button';

export function FormActions({
  primaryLabel,
  showPrimary = true,
  showBack,
  backLabel,
  loading,
  onPrimary,
  onPrev,
}: FormActionsProps) {
  return (
    <div className="flex justify-between gap-2 pt-2">
      {showBack ? (
        <Button type="button" variant="outline" disabled={loading} onClick={onPrev}>
          {backLabel}
        </Button>
      ) : (
        <span />
      )}
      {showPrimary && (
        <Button type="button" disabled={loading} onClick={onPrimary}>
          {primaryLabel}
        </Button>
      )}
    </div>
  );
}
