// packages/vue/src/fields/RadioField.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { FormFieldProps } from '../types';

const props = defineProps<FormFieldProps>();
const emit = defineEmits<{
  (e: 'update:value', value: unknown): void;
  (e: 'blur'): void;
}>();

const groupId = computed(() => `fh-field-${props.field.key}`);
const helperId = computed(() => `fh-field-${props.field.key}-helper`);
</script>

<template>
  <fieldset
    class="fh-field fh-field--radio"
    :aria-invalid="!!props.error || undefined"
    :aria-describedby="(props.error || props.field.helperText) ? helperId : undefined"
  >
    <legend v-if="props.field.label" class="fh-field__label">
      {{ props.field.label }}
    </legend>
    <div class="fh-field__radio-group">
      <div
        v-for="option in (props.field.options ?? [])"
        :key="String(option.value)"
        class="fh-field__radio-option"
      >
        <input
          :id="`${groupId}-${option.value}`"
          class="fh-field__radio"
          type="radio"
          :name="props.field.key"
          :value="option.value"
          :checked="String(props.value) === String(option.value)"
          :disabled="props.disabled || props.loading"
          @change="emit('update:value', option.value)"
        />
        <label :for="`${groupId}-${option.value}`" class="fh-field__radio-label">
          {{ option.label }}
        </label>
      </div>
    </div>
    <p v-if="props.error" :id="helperId" class="fh-field__error">{{ props.error }}</p>
    <p v-else-if="props.field.helperText" :id="helperId" class="fh-field__helper">{{ props.field.helperText }}</p>
  </fieldset>
</template>

// examples/react-shadcn/src/fields/RadioField.tsx
import type { FieldComponentProps } from '@formhaus/react';
import { Label } from '@/components/ui/label';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { FieldShell } from './FieldShell';

export function RadioField({ field, value, error, loading, disabled, onChange }: FieldComponentProps) {
  return (
    <FieldShell field={field} error={error}>
      <RadioGroup
        id={field.key}
        value={typeof value === 'string' ? value : null}
        disabled={disabled || loading}
        aria-invalid={!!error}
        onValueChange={(next) => onChange(next)}
      >
        {(field.options ?? []).map((option) => (
          <Label key={option.value} className="font-normal">
            <RadioGroupItem value={option.value} />
            {option.label}
          </Label>
        ))}
      </RadioGroup>
    </FieldShell>
  );
}
