// packages/vue/src/fields/FieldShell.vue
<script setup lang="ts">
import type { FormField } from '@formhaus/core';
import { computed } from 'vue';
import { fieldAria, fieldIds } from './useField';

const props = defineProps<{
  field: FormField;
  error?: string;
  variant?: 'checkbox' | 'switch' | 'radio' | 'multiselect';
}>();

const group = computed(() => props.variant === 'radio' || props.variant === 'multiselect');
const ids = computed(() => fieldIds(props.field));
</script>

<template>
  <component
    :is="group ? 'fieldset' : 'div'"
    :class="['fh-field', props.variant && `fh-field--${props.variant}`]"
    v-bind="group ? fieldAria(props.field, props.error) : {}"
  >
    <legend v-if="group && props.field.label" class="fh-field__label">
      {{ props.field.label }}
    </legend>
    <div v-if="props.variant" :class="`fh-field__${props.variant}-${group ? 'group' : 'wrapper'}`">
      <slot />
      <label v-if="!group && props.field.label" :for="ids.inputId" class="fh-field__label">
        {{ props.field.label }}
      </label>
    </div>
    <template v-else>
      <label v-if="props.field.label" :for="ids.inputId" class="fh-field__label">
        {{ props.field.label }}
      </label>
      <slot />
    </template>
    <p v-if="props.error" :id="ids.helperId" class="fh-field__error">{{ props.error }}</p>
    <p v-else-if="props.field.helperText" :id="ids.helperId" class="fh-field__helper">{{ props.field.helperText }}</p>
  </component>
</template>

// packages/react/src/fields/FieldShell.tsx
import type { FormField } from '@formhaus/core';
import type { ReactNode } from 'react';
import { FieldLabel } from './FieldLabel';
import { FieldMessage } from './FieldMessage';
import { describedBy } from './fieldProps';

interface FieldShellProps {
  field: FormField;
  error?: string;
  variant?: 'checkbox' | 'switch' | 'radio' | 'multiselect';
  children: ReactNode;
}

export function FieldShell({ field, error, variant, children }: FieldShellProps) {
  const group = variant === 'radio' || variant === 'multiselect';
  const Root = group ? 'fieldset' : 'div';

  return (
    <Root
      className={variant ? `fh-field fh-field--${variant}` : 'fh-field'}
      aria-invalid={group ? !!error || undefined : undefined}
      aria-describedby={group ? describedBy(field, error) : undefined}
    >
      {group && field.label && <legend className="fh-field__label">{field.label}</legend>}
      {variant ? (
        <div className={`fh-field__${variant}-${group ? 'group' : 'wrapper'}`}>
          {children}
          {!group && field.label && (
            <label className="fh-field__label" htmlFor={field.key}>
              {field.label}
            </label>
          )}
        </div>
      ) : (
        <>
          <FieldLabel field={field} inputId={field.key} />
          {children}
        </>
      )}
      <FieldMessage field={field} error={error} />
    </Root>
  );
}
