// packages/vue/src/fields/MultiselectField.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { FormFieldProps } from '../types';

const props = defineProps<FormFieldProps>();
const emit = defineEmits<{
  (e: 'update:value', value: unknown): void;
  (e: 'blur'): void;
}>();

const groupId = computed(() => `fh-field-${props.field.key}`);
const helperId = computed(() => `fh-field-${props.field.key}-helper`);
const selected = computed(() =>
  Array.isArray(props.value) ? (props.value as (string | number)[]) : [],
);

function handleToggle(optValue: string) {
  const next = selected.value.includes(optValue)
    ? selected.value.filter((v) => v !== optValue)
    : [...selected.value, optValue];
  emit('update:value', next);
}
</script>

<template>
  <fieldset
    class="fh-field fh-field--multiselect"
    :aria-invalid="!!props.error || undefined"
    :aria-describedby="(props.error || props.field.helperText) ? helperId : undefined"
  >
    <legend v-if="props.field.label" class="fh-field__label">
      {{ props.field.label }}
    </legend>
    <div class="fh-field__multiselect-group">
      <div
        v-for="option in (props.field.options ?? [])"
        :key="String(option.value)"
        class="fh-field__multiselect-option"
      >
        <input
          :id="`${groupId}-${option.value}`"
          class="fh-field__checkbox"
          type="checkbox"
          :checked="selected.includes(option.value)"
          :disabled="props.disabled || props.loading"
          @change="handleToggle(option.value)"
          @blur="emit('blur')"
        />
        <label :for="`${groupId}-${option.value}`" class="fh-field__multiselect-label">
          {{ option.label }}
        </label>
      </div>
    </div>
    <p v-if="props.error" :id="helperId" class="fh-field__error">{{ props.error }}</p>
    <p v-else-if="props.field.helperText" :id="helperId" class="fh-field__helper">{{ props.field.helperText }}</p>
  </fieldset>
</template>

// packages/react/src/fields/MultiselectField.tsx
import type { FieldComponentProps } from '../types';

export function MultiselectField({
  field,
  value,
  error,
  loading,
  disabled,
  onChange,
  onBlur,
}: FieldComponentProps) {
  const groupId = field.key;
  const helperId = `${field.key}-helper`;
  const errorId = `${field.key}-error`;
  const describedBy = error ? errorId : field.helperText ? helperId : undefined;
  const options = field.options ?? [];
  const selected = Array.isArray(value) ? (value as (string | number)[]) : [];

  function handleToggle(optValue: string) {
    const next = selected.includes(optValue)
      ? selected.filter((v) => v !== optValue)
      : [...selected, optValue];
    onChange(next);
  }

  return (
    <fieldset
      className="fh-field fh-field--multiselect"
      aria-invalid={!!error || undefined}
      aria-describedby={describedBy}
    >
      {field.label && <legend className="fh-field__label">{field.label}</legend>}
      <div className="fh-field__multiselect-group">
        {options.map((opt) => {
          const optionId = `${groupId}-${opt.value}`;
          return (
            <div key={opt.value} className="fh-field__multiselect-option">
              <input
                id={optionId}
                type="checkbox"
                className="fh-field__checkbox"
                checked={selected.includes(opt.value)}
                disabled={disabled || loading}
                onChange={() => handleToggle(opt.value)}
                onBlur={onBlur}
              />
              <label className="fh-field__multiselect-label" htmlFor={optionId}>
                {opt.label}
              </label>
            </div>
          );
        })}
      </div>
      {error && (
        <p id={errorId} className="fh-field__error" role="alert">
          {error}
        </p>
      )}
      {!error && field.helperText && (
        <p id={helperId} className="fh-field__helper">
          {field.helperText}
        </p>
      )}
    </fieldset>
  );
}
