// packages/vue/src/fields/RadioField.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { FormFieldProps } from '../types';

const props = defineProps<FormFieldProps>();
const emit = defineEmits<{
  (e: 'update:value', value: unknown): void;
  (e: 'blur'): void;
}>();

const groupId = computed(() => `fh-field-${props.field.key}`);
const helperId = computed(() => `fh-field-${props.field.key}-helper`);
</script>

<template>
  <fieldset
    class="fh-field fh-field--radio"
    :aria-invalid="!!props.error || undefined"
    :aria-describedby="(props.error || props.field.helperText) ? helperId : undefined"
  >
    <legend v-if="props.field.label" class="fh-field__label">
      {{ props.field.label }}
    </legend>
    <div class="fh-field__radio-group">
      <div
        v-for="option in (props.field.options ?? [])"
        :key="String(option.value)"
        class="fh-field__radio-option"
      >
        <input
          :id="`${groupId}-${option.value}`"
          class="fh-field__radio"
          type="radio"
          :name="props.field.key"
          :value="option.value"
          :checked="String(props.value) === String(option.value)"
          :disabled="props.disabled || props.loading"
          @change="emit('update:value', option.value)"
        />
        <label :for="`${groupId}-${option.value}`" class="fh-field__radio-label">
          {{ option.label }}
        </label>
      </div>
    </div>
    <p v-if="props.error" :id="helperId" class="fh-field__error">{{ props.error }}</p>
    <p v-else-if="props.field.helperText" :id="helperId" class="fh-field__helper">{{ props.field.helperText }}</p>
  </fieldset>
</template>

// packages/react/src/fields/RadioField.tsx
import type { FieldComponentProps } from '../types';

export function RadioField({
  field,
  value,
  error,
  loading,
  disabled,
  onChange,
  onBlur,
}: FieldComponentProps) {
  const groupId = field.key;
  const helperId = `${field.key}-helper`;
  const errorId = `${field.key}-error`;
  const describedBy = error ? errorId : field.helperText ? helperId : undefined;
  const options = field.options ?? [];

  return (
    <fieldset
      className="fh-field fh-field--radio"
      aria-invalid={!!error || undefined}
      aria-describedby={describedBy}
    >
      {field.label && <legend className="fh-field__label">{field.label}</legend>}
      <div className="fh-field__radio-group">
        {options.map((opt) => {
          const optionId = `${groupId}-${opt.value}`;
          return (
            <div key={opt.value} className="fh-field__radio-option">
              <input
                id={optionId}
                type="radio"
                className="fh-field__radio"
                name={groupId}
                value={opt.value}
                checked={String(value) === String(opt.value)}
                disabled={disabled || loading}
                onChange={() => onChange(opt.value)}
                onBlur={onBlur}
              />
              <label className="fh-field__radio-label" htmlFor={optionId}>
                {opt.label}
              </label>
            </div>
          );
        })}
      </div>
      {error && (
        <p id={errorId} className="fh-field__error" role="alert">
          {error}
        </p>
      )}
      {!error && field.helperText && (
        <p id={helperId} className="fh-field__helper">
          {field.helperText}
        </p>
      )}
    </fieldset>
  );
}
