// examples/vue-vuetify/src/actions/StepProgress.vue
<script setup>
import { computed } from 'vue';

const props = defineProps({
  current: { type: Number, required: true },
  total: { type: Number, required: true },
  stepTitle: { type: String, default: undefined },
  stepDescription: { type: String, default: undefined },
});

const percent = computed(() => (props.current / props.total) * 100);
</script>

<template>
  <div style="display: flex; flex-direction: column; gap: 8px; margin-bottom: 16px">
    <v-progress-linear :model-value="percent" color="primary" rounded />
    <span class="text-caption text-medium-emphasis">
      Step {{ current }} of {{ total }}
    </span>
    <h3 v-if="stepTitle" class="text-h6" style="margin: 0">{{ stepTitle }}</h3>
    <p v-if="stepDescription" class="text-body-2 text-medium-emphasis" style="margin: 0">
      {{ stepDescription }}
    </p>
  </div>
</template>

// examples/react-mui/src/actions/StepProgress.tsx
import type { FormStepProgressProps } from '@formhaus/react';
import Box from '@mui/material/Box';
import LinearProgress from '@mui/material/LinearProgress';
import Typography from '@mui/material/Typography';

export function StepProgress({
  current,
  total,
  stepTitle,
  stepDescription,
}: FormStepProgressProps) {
  const percent = (current / total) * 100;

  return (
    <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1, mb: 2 }}>
      <LinearProgress variant="determinate" value={percent} />
      <Typography variant="caption" color="text.secondary">
        Step {current} of {total}
      </Typography>
      {stepTitle && (
        <Typography variant="h6" sx={{ mt: 0.5 }}>
          {stepTitle}
        </Typography>
      )}
      {stepDescription && (
        <Typography variant="body2" color="text.secondary">
          {stepDescription}
        </Typography>
      )}
    </Box>
  );
}
