// examples/react-shadcn/src/fields/SelectField.tsx
import type { FieldComponentProps } from '@formhaus/react';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { FieldShell } from './FieldShell';

export function SelectField({ field, value, error, loading, disabled, onChange }: FieldComponentProps) {
  const options = field.options ?? [];

  return (
    <FieldShell field={field} error={error}>
      <Select
        items={options}
        value={typeof value === 'string' && value !== '' ? value : null}
        disabled={disabled || loading}
        onValueChange={(next) => onChange(next ?? '')}
      >
        <SelectTrigger id={field.key} className="w-full" aria-invalid={!!error}>
          <SelectValue placeholder={field.placeholder ?? 'Select...'} />
        </SelectTrigger>
        <SelectContent>
          {options.map((option) => (
            <SelectItem key={option.value} value={option.value}>
              {option.label}
            </SelectItem>
          ))}
        </SelectContent>
      </Select>
    </FieldShell>
  );
}

// packages/vue/src/fields/SelectField.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { FormFieldProps } from '../types';

const props = defineProps<FormFieldProps>();
const emit = defineEmits<{
  (e: 'update:value', value: unknown): void;
  (e: 'blur'): void;
}>();

const inputId = computed(() => `fh-field-${props.field.key}`);
const helperId = computed(() => `fh-field-${props.field.key}-helper`);

function onChange(event: Event) {
  emit('update:value', (event.target as HTMLSelectElement).value);
}
</script>

<template>
  <div class="fh-field">
    <label v-if="props.field.label" :for="inputId" class="fh-field__label">
      {{ props.field.label }}
    </label>
    <select
      :id="inputId"
      class="fh-field__input"
      :value="String(props.value ?? '')"
      :disabled="props.disabled || props.loading"
      :aria-invalid="!!props.error || undefined"
      :aria-describedby="(props.error || props.field.helperText) ? helperId : undefined"
      @change="onChange"
    >
      <option v-if="props.field.placeholder" value="" disabled>
        {{ props.field.placeholder }}
      </option>
      <option
        v-for="option in (props.field.options ?? [])"
        :key="String(option.value)"
        :value="option.value"
      >
        {{ option.label }}
      </option>
    </select>
    <p v-if="props.error" :id="helperId" class="fh-field__error">{{ props.error }}</p>
    <p v-else-if="props.field.helperText" :id="helperId" class="fh-field__helper">{{ props.field.helperText }}</p>
  </div>
</template>
