// examples/react-mui/src/fields/RadioField.tsx
import type { FieldComponentProps } from '@formhaus/react';
import FormControl from '@mui/material/FormControl';
import FormControlLabel from '@mui/material/FormControlLabel';
import FormHelperText from '@mui/material/FormHelperText';
import FormLabel from '@mui/material/FormLabel';
import Radio from '@mui/material/Radio';
import RadioGroup from '@mui/material/RadioGroup';

export function RadioField({
  field,
  value,
  error,
  loading,
  disabled,
  onChange,
}: FieldComponentProps) {
  return (
    <FormControl error={!!error} disabled={disabled || loading} sx={{ mt: 1, mb: 0.5 }}>
      <FormLabel id={`${field.key}-label`}>{field.label}</FormLabel>
      <RadioGroup
        aria-labelledby={`${field.key}-label`}
        value={(value as string) ?? ''}
        onChange={(e) => onChange(e.target.value)}
      >
        {(field.options ?? []).map((opt) => (
          <FormControlLabel key={opt.value} value={opt.value} control={<Radio />} label={opt.label} />
        ))}
      </RadioGroup>
      {error && <FormHelperText>{error}</FormHelperText>}
      {!error && field.helperText && <FormHelperText>{field.helperText}</FormHelperText>}
    </FormControl>
  );
}

// examples/vue-vuetify/src/fields/RadioField.vue
<script setup>
defineProps({
  field: { type: Object, required: true },
  value: { default: undefined },
  error: { type: String, default: undefined },
  loading: { type: Boolean, default: false },
  disabled: { type: Boolean, default: false },
});

const emit = defineEmits(['update:value', 'blur', 'focus']);
</script>

<template>
  <v-radio-group
    :model-value="value ?? ''"
    :error-messages="error ? [error] : []"
    :hint="field.helperText"
    :persistent-hint="!!field.helperText"
    :disabled="disabled || loading"
    :label="field.label"
    @update:model-value="(v) => emit('update:value', v)"
    @blur="emit('blur')"
    @focus="emit('focus')"
  >
    <v-radio
      v-for="opt in (field.options ?? [])"
      :key="opt.value"
      :label="opt.label"
      :value="opt.value"
    />
  </v-radio-group>
</template>
