// examples/react-mui/src/fields/SelectField.tsx
import type { FieldComponentProps } from '@formhaus/react';
import MuiTextField from '@mui/material/TextField';
import MenuItem from '@mui/material/MenuItem';

export function SelectField({
  field,
  value,
  error,
  loading,
  disabled,
  onChange,
}: FieldComponentProps) {
  const options = field.options ?? [];
  const isMulti = field.type === 'multiselect';
  const selectValue = isMulti
    ? Array.isArray(value) ? value : []
    : (value as string) ?? '';

  return (
    <MuiTextField
      id={field.key}
      label={field.label}
      select
      value={selectValue}
      onChange={(e) => onChange(e.target.value)}
      error={!!error}
      helperText={error || field.helperText}
      disabled={disabled || loading}
      fullWidth
      margin="normal"
      slotProps={{
        select: { multiple: isMulti },
      }}
    >
      {!isMulti && (
        <MenuItem value="">
          {field.placeholder || 'Select...'}
        </MenuItem>
      )}
      {options.map((opt) => (
        <MenuItem key={opt.value} value={opt.value}>
          {opt.label}
        </MenuItem>
      ))}
    </MuiTextField>
  );
}

// examples/vue-vuetify/src/fields/SelectField.vue
<script setup>
const props = defineProps({
  field: { type: Object, required: true },
  value: { default: undefined },
  error: { type: String, default: undefined },
  loading: { type: Boolean, default: false },
  disabled: { type: Boolean, default: false },
});

const emit = defineEmits(['update:value', 'blur', 'focus']);

const isMulti = props.field.type === 'multiselect';
</script>

<template>
  <v-select
    :id="field.key"
    :label="field.label"
    :model-value="isMulti ? (Array.isArray(value) ? value : []) : (value ?? '')"
    :items="field.options ?? []"
    item-title="label"
    item-value="value"
    :multiple="isMulti"
    :placeholder="field.placeholder || 'Select...'"
    :error-messages="error ? [error] : []"
    :hint="field.helperText"
    :persistent-hint="!!field.helperText"
    :disabled="disabled || loading"
    @update:model-value="(v) => emit('update:value', v)"
    @blur="emit('blur')"
    @focus="emit('focus')"
  />
</template>
