// examples/react-mui/src/fields/TextareaField.tsx
import type { FieldComponentProps } from '@formhaus/react';
import MuiTextField from '@mui/material/TextField';

export function TextareaField({
  field,
  value,
  error,
  loading,
  disabled,
  onChange,
}: FieldComponentProps) {
  return (
    <MuiTextField
      id={field.key}
      label={field.label}
      value={(value as string) ?? ''}
      placeholder={field.placeholder}
      onChange={(e) => onChange(e.target.value)}
      error={!!error}
      helperText={error || field.helperText}
      disabled={disabled || loading}
      fullWidth
      multiline
      minRows={field.rows ?? 3}
      margin="normal"
    />
  );
}

// examples/vue-vuetify/src/fields/TextareaField.vue
<script setup>
defineProps({
  field: { type: Object, required: true },
  value: { default: undefined },
  error: { type: String, default: undefined },
  loading: { type: Boolean, default: false },
  disabled: { type: Boolean, default: false },
});

const emit = defineEmits(['update:value', 'blur', 'focus']);
</script>

<template>
  <v-textarea
    :id="field.key"
    :label="field.label"
    :model-value="(value ?? '')"
    :placeholder="field.placeholder"
    :rows="field.rows ?? 3"
    :error-messages="error ? [error] : []"
    :hint="field.helperText"
    :persistent-hint="!!field.helperText"
    :disabled="disabled || loading"
    @update:model-value="(v) => emit('update:value', v)"
    @blur="emit('blur')"
    @focus="emit('focus')"
  />
</template>
