// examples/react-mui/src/fields/TextField.tsx
import type { FieldComponentProps } from '@formhaus/react';
import MuiTextField from '@mui/material/TextField';

export function TextField({
  field,
  value,
  error,
  loading,
  disabled,
  onChange,
}: FieldComponentProps) {
  const inputType =
    field.type === 'email' ? 'email'
    : field.type === 'password' ? 'password'
    : field.type === 'number' ? 'number'
    : field.type === 'date' ? 'date'
    : field.type === 'phone' ? 'tel'
    : 'text';

  return (
    <MuiTextField
      id={field.key}
      label={field.label}
      type={inputType}
      value={value != null ? String(value) : ''}
      placeholder={field.placeholder}
      onChange={(e) => onChange(field.type === 'number' ? Number(e.target.value) : e.target.value)}
      error={!!error}
      helperText={error || field.helperText}
      disabled={disabled || loading}
      fullWidth
      margin="normal"
      slotProps={{
        inputLabel: field.type === 'date' ? { shrink: true } : undefined,
      }}
    />
  );
}

// examples/vue-vuetify/src/fields/TextField.vue
<script setup>
const props = defineProps({
  field: { type: Object, required: true },
  value: { default: undefined },
  error: { type: String, default: undefined },
  loading: { type: Boolean, default: false },
  disabled: { type: Boolean, default: false },
});

const emit = defineEmits(['update:value', 'blur', 'focus']);

const inputType =
  props.field.type === 'email' ? 'email'
  : props.field.type === 'password' ? 'password'
  : props.field.type === 'number' ? 'number'
  : props.field.type === 'date' ? 'date'
  : props.field.type === 'phone' ? 'tel'
  : 'text';
</script>

<template>
  <v-text-field
    :id="field.key"
    :label="field.label"
    :type="inputType"
    :model-value="value != null ? String(value) : ''"
    :placeholder="field.placeholder"
    :error-messages="error ? [error] : []"
    :hint="field.helperText"
    :persistent-hint="!!field.helperText"
    :disabled="disabled || loading"
    @update:model-value="(v) => emit('update:value', field.type === 'number' ? Number(v) : v)"
    @blur="emit('blur')"
    @focus="emit('focus')"
  />
</template>
