// examples/react-mui/src/actions/FormActions.tsx
import type { FormActionsProps } from '@formhaus/react';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';

export function FormActions({
  primaryLabel,
  showPrimary = true,
  showBack,
  backLabel,
  cancelAction,
  loading,
  onPrimary,
  onPrev,
  onCancel,
}: FormActionsProps) {
  return (
    <Box sx={{ display: 'flex', justifyContent: 'space-between', gap: 1, pt: 2 }}>
      <Box sx={{ display: 'flex', gap: 1 }}>
        {showBack && (
          <Button variant="outlined" disabled={loading} onClick={onPrev}>
            {backLabel}
          </Button>
        )}
        {cancelAction && (
          <Button variant="text" disabled={loading} onClick={onCancel}>
            {cancelAction.label}
          </Button>
        )}
      </Box>
      {showPrimary && (
        <Button variant="contained" disabled={loading} onClick={onPrimary}>
          {primaryLabel}
        </Button>
      )}
    </Box>
  );
}

// examples/vue-vuetify/src/actions/FormActions.vue
<script setup>
defineProps({
  primaryLabel: { type: String, default: undefined },
  showPrimary: { type: Boolean, default: true },
  showBack: { type: Boolean, default: false },
  backLabel: { type: String, default: undefined },
  cancelAction: { type: Object, default: undefined },
  loading: { type: Boolean, default: false },
});

const emit = defineEmits(['primary', 'prev', 'cancel']);
</script>

<template>
  <div style="display: flex; justify-content: space-between; gap: 8px; padding-top: 16px">
    <div style="display: flex; gap: 8px">
      <v-btn v-if="showBack" variant="outlined" :disabled="loading" @click="emit('prev')">
        {{ backLabel }}
      </v-btn>
      <v-btn v-if="cancelAction" variant="text" :disabled="loading" @click="emit('cancel')">
        {{ cancelAction.label }}
      </v-btn>
    </div>
    <v-btn v-if="showPrimary" color="primary" :loading="loading" @click="emit('primary')">
      {{ primaryLabel }}
    </v-btn>
  </div>
</template>
